---
title: "Bandelier Calibration"
output: pdf_document
date: "2024-03-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(terra)
library(here)
library(ggplot2)
library(dplyr)
library(fuelsgen)
source('~/Desktop/R tools/unit_xform.R')
source('~/Desktop/R tools/Metro_Hastings_Stochastic.R')
```

Do clustering of scan and grid locations

```{r, echo=F}
load(here('examples/bandelier/results/topology_df.RData'))
load(here('examples/bandelier/results/plot_nshrub.RData'))
# plot topo has 157 entries, but we only have fuels data for 155 entries, we are missing files for plot 1 and plot 143 remove these here for now
plot_topo = plot_topo %>% filter(!(Plot %in% c(1,143))); plot_topo$Plot = NULL
nplot = nrow(plot_topo)
# get coverage for plot_topo
load(here('examples/bandelier/results/plot_coverage.RData'))
plot_topo$coverage = coverage; rm(coverage); plot_topo = plot_topo[,c(1,2,3,6,4,5)]

all_topo = as.data.frame(unit_xform(rbind(plot_topo,grid_topo)))
all_topo$coverage = c(plot_topo$coverage,grid_topo$coverage)
all_topo$type = c(rep('plot',nrow(plot_topo)),rep('grid',nrow(grid_topo)))

ggplot(all_topo) + geom_point(aes(x_crd,y_crd,col=coverage,shape=type)) + scale_color_viridis_c()

my_dist = function(X,w=rep(1,ncol(X))){
  # slow and expensive, but it doesn't really matter for this application
  names = colnames(X)
  X = t(t(X) * sqrt(w))
  if(!('aspect' %in% names)){
    return(dist(X))
  } else{
    d = as.matrix(dist(X))
    which_aspect = which(names=='aspect')
    aspect_d = as.matrix(dist(X[,which_aspect,drop=F]))
    fix = which(aspect_d>.5) # fix any aspects that are greater than .5 apart
    d[fix] = sqrt(d[fix]^2-aspect_d[fix]^2) # remove the aspect part of the distance calculation from these points
    aspect_d = pmin(aspect_d,1-aspect_d)
    d[fix] = sqrt(d[fix]^2 + aspect_d[fix]^2)
    return(as.dist(d))
  }
}

# search all possible combinations of these 6 parameters for clustering
which.X.cl = list()
for(i in 1:3){
  which.X.cl[[i]] = t(combn(c('slope','aspect','elevation'),i))
}
for(i in 1:3){
  for(j in 1:nrow(which.X.cl[[i]])){
    id = which.X.cl[[i]][j,]
    w = numeric(length(id))+1
    for(k in 1:length(id)){
      if(id[k]%in%c('x_crd','y_crd')){
        w[k] = .05
      }
    }
    d = my_dist(all_topo[,id],w)
    cl.model = hclust(d)
    cl = cutree(cl.model,3)
    all_topo$cl = cl
    cl.dens = data.frame(d=nshrub,clust=cl[1:nplot])
    print(ggplot(cl.dens) + geom_point(aes(as.factor(clust),d)) + labs(title=paste(which.X.cl[[i]][j,],collapse = ', ')))
  }
}

# I like slope, aspect, coverage when coverage is available
which.X.cl.naip = c('slope','aspect','coverage')
d.naip = my_dist(all_topo[,which.X.cl.naip])

cl.model.naip = hclust(d.naip)
cl.naip = cutree(cl.model.naip,3)
all_topo$cl.naip = cl.naip
cl.dens.naip = data.frame(d=nshrub,clust=cl.naip[1:nplot])
print(ggplot(cl.dens.naip) + geom_point(aes(as.factor(clust),d)) + labs(title=paste(which.X.cl.naip,collapse = ', ')))
    
# When coverage is not available, I like slope and x_crd or y_crd, they are both about the same
which.X.cl = c('aspect')
d = my_dist(all_topo[,which.X.cl],w = c(1))

cl.model = hclust(d)
cl = cutree(cl.model,3)
all_topo$cl = cl
cl.dens = data.frame(d=nshrub,clust=cl[1:nplot])
print(ggplot(cl.dens) + geom_point(aes(as.factor(clust),d)) + labs(title=paste(which.X.cl,collapse = ', ')))
```

```{r vis clusters, echo=F}
ggplot(all_topo) + geom_point(aes(x=x_crd,y=y_crd,col=as.factor(cl),pch=as.factor(type)))
ggplot(subset(all_topo,type=='plot')) + geom_point(aes(x=x_crd,y=y_crd,col=as.factor(cl)))
ggplot(cl.dens) + geom_boxplot(aes(as.factor(clust),d))

ggplot(all_topo) + geom_point(aes(x=x_crd,y=y_crd,col=as.factor(cl.naip),pch=as.factor(type)))
ggplot(subset(all_topo,type=='plot')) + geom_point(aes(x=x_crd,y=y_crd,col=as.factor(cl.naip)))
ggplot(cl.dens.naip) + geom_boxplot(aes(as.factor(clust),d))
```
Put fuel objects into clusters for calibration

```{r, echo=FALSE}
load(here('examples/bandelier/results/plot_data.RData'))
ncl = 3
data.cl = vector(mode='list',length=ncl)
data.cl.naip = vector(mode='list',length=ncl)
cl.plot = cl[1:nplot]
cl.plot.naip = cl.naip[1:nplot]
for(i in 1:ncl){
  data.cl[[i]] = gen_fuels(dimX = 20, dimY = 20,
                           density = .05,        # shrubs per unit area
                           heterogeneity = 3,     # level of heterogeneity in shrub placement
                           heterogeneity.scale = 1,      # scale of the mean-zero GP realization
                           radius = 1, sd_radius = .1,  # normal distribution parameters for shrub radius
                           height = NULL, sd_height = 0, # normal distribution parameters for shrub height
                           reps=1,                      # number of random maps to generate
                           GP.init.size=32,             # How densely to sample GP (n^3 scaling, <=1000 is pretty fast)
                           seed=10,                      # random seed for reproducibility
                           parallel=F)
  data.cl[[i]]$dat = data$dat[cl.plot==i]
  data.cl[[i]]$reps = length(data.cl[[i]]$dat)
  data.cl[[i]]$mets = mets
  data.cl[[i]]$mets$mets = data.cl[[i]]$mets$mets[cl.plot==i,]
  data.cl[[i]]$nshrub = numeric(data.cl[[i]]$reps)
  for(k in 1:data.cl[[i]]$reps){
    data.cl[[i]]$nshrub[k] = nrow(data.cl[[i]]$dat[[k]])
  }
  data.cl.naip[[i]] = gen_fuels(dimX = 20, dimY = 20,
                                 density = .05,        # shrubs per unit area
                                 heterogeneity = 3,     # level of heterogeneity in shrub placement
                                 heterogeneity.scale = 1,      # scale of the mean-zero GP realization
                                 radius = 1, sd_radius = .1,  # normal distribution parameters for shrub radius
                                 height = NULL, sd_height = 0, # normal distribution parameters for shrub height
                                 reps=1,                      # number of random maps to generate
                                 GP.init.size=100,             # How densely to sample GP (n^3 scaling, <=1000 is pretty fast)
                                 seed=10,                      # random seed for reproducibility
                                 parallel=F)
    
  data.cl.naip[[i]]$dat = data$dat[cl.plot.naip==i]
  data.cl.naip[[i]]$reps = length(data.cl.naip[[i]]$dat)
  data.cl.naip[[i]]$nshrub = numeric(data.cl.naip[[i]]$reps)
  for(k in 1:data.cl.naip[[i]]$reps){
    data.cl.naip[[i]]$nshrub[k] = nrow(data.cl.naip[[i]]$dat[[k]])
  }
  data.cl.naip[[i]]$mets = mets
  data.cl.naip[[i]]$mets$mets = data.cl.naip[[i]]$mets$mets[cl.plot.naip==i,]
}
```

Calibration

```{r, echo=F}
# prior = 
# prior.naip = vector(mode='list',length = ncl)
# mcmc = mcmc.naip = vector(mode='list',length = ncl)
# mcmc.naip = vector(mode='list',length = ncl)
for(i in 1:ncl){
  # if(data.cl[[i]]$reps<10){
  #   # not enough observations to estimate the covariance matrix augment with simulations
  #   prior[[i]] = get_prior_info(data.cl[[i]],data.cl[[i]]$mets,est_cov_obs = F)
  # } else{
  #   prior[[i]] = get_prior_info(data.cl[[i]],data.cl[[i]]$mets)
  # }
  # save(prior,file=here('examples/bandelier/results/mcmc/prior_all_cl.RData'))
  # load(here('examples/bandelier/results/mcmc/prior_all_cl.RData'))
  # mcmc[[i]] = mcmc(data.cl[[i]]$mets,data.cl[[i]],prior[[i]],paste0(here('examples/bandelier/results/mcmc/calib_cl_'),i,'.RData'),
  #                 n.samples=5000,n.burn=0,gen_reps=25,avg='mets',
  #                 gen_parallel=F,mets_parallel=T,verbose=100,load.theta=F,update.every=1)
  # mcmc[[i]] = mcmc_mh_adaptive = fuelsgen:::mcmc_MH_adaptive(data.cl[[i]]$mets,data.cl[[i]],prior[[i]],
  #                                               paste0(here('examples/bandelier/results/mcmc/calib_cl_'),i,'.RData'),
  #                                               adapt.par = c(100,20,.5,.75),
  #                                               n.samples=5000,n.burn=0,gen_reps=25,avg='mets',
  #                                               gen_parallel=F,mets_parallel=T,verbose=T)
  
  if(data.cl.naip[[i]]$reps<10){
    # not enough observations to estimate the covariance matrix augment with simulations
    # prior.naip[[i]] = get_prior_info(data.cl.naip[[i]],data.cl.naip[[i]]$mets,est_cov_obs = F)
  } else{
    # prior.naip[[i]] = get_prior_info(data.cl.naip[[i]],data.cl.naip[[i]]$mets)
  }
  # save(prior.naip,file=here('examples/bandelier/results/mcmc/prior_naip_all_cl.RData'))
  # load(here('examples/bandelier/results/mcmc/prior_naip_all_cl.RData'))
  # mcmc.naip[[i]] = mcmc(y_obs,fuel,prior,paste0(here('examples/bandelier/results/mcmc/naip_calib_cl_'),i,'.RData'),
  #                       n.samples=100,n.burn=0,gen_reps=25,avg='mets',
  #                       gen_parallel=F,mets_parallel=T,verbose=10,load.theta=F,update.every=1)
  # mcmc.naip[[i]] = fuelsgen:::mcmc_MH_adaptive(data.cl.naip[[i]]$mets,data.cl.naip[[i]],prior.naip[[i]],
  #                                               paste0(here('examples/bandelier/results/mcmc/calib_naip_cl_'),i,'.RData'),
  #                                               adapt.par = c(100,20,.5,.5),
  #                                               n.samples=10000,n.burn=0,gen_reps=25,avg='mets',
  #                                               gen_parallel=F,mets_parallel=T,verbose=T)
}
```


# naip calibration results

```{r, echo=F}
load(here('examples/bandelier/results/mcmc/prior_naip_all_cl.RData'))

par(mfrow=c(2,2))
ncl = 3
for(j in 1:ncl){
  load(paste0(here('examples/bandelier/results/mcmc/calib_naip_cl_'),j,'.RData'))
  for(i in 1:4){
    plot(density(mcmc$trace[(.5*10000):10000,i],from=prior.naip[[j]]$prior_params$lb[i],to=prior.naip[[j]]$prior_params$ub[i]),
         main='',xlab=mcmc$par_names[i])
    abline(v=prior.naip[[j]]$theta_est[i],col='red')
  }
  for(i in 1:4){
    plot(mcmc$trace[(.5*10000):10000,i],type='l',
         main='',xlab=mcmc$par_names[i],ylab='')
    abline(h=prior.naip[[j]]$theta_est[i],col='red')
  }
}
j=1;i=4
load(paste0(here('examples/bandelier/results/mcmc/calib_naip_cl_'),j,'.RData'))
plot(density(mcmc$trace[(.5*10000):10000,i],from=0),xlim=c(0,.1),ylim=c(0,350),
        main='',xlab=mcmc$par_names[i],col='red');abline(v=prior.naip[[j]]$theta_est[i],col='red')
j=2;
load(paste0(here('examples/bandelier/results/mcmc/calib_naip_cl_'),j,'.RData'))
lines(density(mcmc$trace[(.5*10000):10000,i],from=0),col='green3',
        main='',xlab=mcmc$par_names[i]);abline(v=prior.naip[[j]]$theta_est[i],col='green3')
j=3;
load(paste0(here('examples/bandelier/results/mcmc/calib_naip_cl_'),j,'.RData'))
lines(density(mcmc$trace[(.5*10000):10000,i],from=0),col='blue',
        main='',xlab=mcmc$par_names[i]);abline(v=prior.naip[[j]]$theta_est[i],col='blue')
```

# no naip calibration results

```{r, echo=F}
load(here('examples/bandelier/results/mcmc/prior_all_cl.RData'))
par(mfrow=c(2,2))
ncl = 3
for(j in 1:ncl){
  load(paste0(here('examples/bandelier/results/mcmc/calib_cl_'),j,'.RData'))
  for(i in 1:4){
    plot(density(mcmc$trace[(.75*5000):5000,i],from=prior[[j]]$prior_params$lb[i],to=prior[[j]]$prior_params$ub[i]),
         main='',xlab=mcmc$par_names[i])
    abline(v=prior[[j]]$theta_est[i],col='red')
  }
  # for(i in 1:4){
  #   plot(mcmc$trace[(.75*5000):5000,i],type='l',
  #        main='',xlab=mcmc$par_names[i])
  #   abline(h=prior[[j]]$theta_est[i],col='red')
  # }
}
par(mfrow=c(1,1))
j=1;i=4
load(paste0(here('examples/bandelier/results/mcmc/calib_cl_'),j,'.RData'))
plot(density(mcmc$trace[(.75*5000):5000,i],from=0),xlim=c(0,.1),ylim=c(0,350),
        main='',xlab=mcmc$par_names[i],col='red');abline(v=prior[[j]]$theta_est[i],col='red')
# hist(data.cl[[j]]$nshrub,freq=F,add=T)
j=2;
load(paste0(here('examples/bandelier/results/mcmc/calib_cl_'),j,'.RData'))
lines(density(mcmc$trace[(.75*5000):5000,i],from=0),col='green2',
        main='',xlab=mcmc$par_names[i]);abline(v=prior[[j]]$theta_est[i],col='green2')
j=3;
load(paste0(here('examples/bandelier/results/mcmc/calib_cl_'),j,'.RData'))
lines(density(mcmc$trace[(.75*5000):5000,i],from=0),col='blue',
        main='',xlab=mcmc$par_names[i]);abline(v=prior[[j]]$theta_est[i],col='blue')
legend('topright',legend=c('1','2','3'),col=c('red','green2','blue'),lty=1)
```

# generate naip fuels

```{r, echo=F}
reps = 10
params = matrix(nrow=reps,ncol=4)
fuels = vector(mode='list',length=nrow(all_topo))
for(j in 1:nrow(all_topo)){
  fuels[[j]] = vector(mode='list',length=reps)
  # for each grid cell generate fuels w.r.t. cluster membership
  cluster = all_topo$cl.naip[j]
  load(paste0(here('examples/bandelier/results/mcmc/calib_naip_cl_'),cluster,'.RData'))
  params = mcmc$trace[sample(1:nrow(mcmc$trace),10,F),]
  for(i in 1:reps){
     fuels[[j]][[i]] = gen_fuels(20,20,params[i,4],params[i,2],params[i,3],1,0,params[i,1])
  }
}
save(fuels,file='~/fuelsgen/examples/bandelier/generated fuels/naip_fuelsgen_object.RData')

# linear model from radius to height
r = h = numeric()
for(i in 1:length(data$dat)){
  r = c(r,data$dat[[i]]$r)
  h = c(h,data$dat[[i]]$h)
}
df_rh = data.frame(r=r,h=h)
h3 = which(h>2.99)
df_rh$h3 = 0
df_rh$h3[h3] = 1
mod_rh = lm(h~1+r,df_rh) # model using all data
mod_rh_3 = lm(h~1+r,subset(df_rh,h3==0)) # model not including data where heights have been truncated

plot(df_rh$r,df_rh$h,xlim=c(0,3),ylim=c(0,3))
lines(df_rh$r,mod_rh$fitted.values,col='red')
lines(df_rh$r[df_rh$h3==0],mod_rh_3$fitted.values,col='blue')

# convert to 10 data frames and sample heights
Xmax = 1000 # (coords to 1020)
Ymax = 940 # coords to 960
dfs = vector(mode='list',length=10)
for(i in 1:10){
  for(j in 156:nrow(all_topo)){ # accidentally generated fuels for plot [1:155] locations, only need grid locations [156:2603]
    dfs[[i]] = rbind(dfs[[i]],data.frame(X=fuels[[j]][[i]]$dat[[1]]$X + (all_topo$x_crd[j] * Xmax),
                                         Y=fuels[[j]][[i]]$dat[[1]]$Y + (all_topo$y_crd[j] * Ymax),
                                         r=fuels[[j]][[i]]$dat[[1]]$r))
  }
  # sample from truncated normal for heights
  # rs = predict(mod_rh,data.frame(r=dfs[[i]]$r))
  # for(k in 1:length(rs)){
  #   dfs[[i]]$h[k] = truncdist::rtrunc(1,'norm',a=1,b=3,mean=rs[k],sd=sigma(mod_rh))
  # }
}

pdf(paste0('~/fuelsgen/examples/bandelier/generated_fuels/naip/gen_','all','.pdf'),width = 10,height = 9.4)
par(mfrow=c(3,4),mar=c(1,1,1,1))
for(i in 1:10){
  plot(dfs[[i]]$X,dfs[[i]]$Y,pch=16,cex=.2,asp=Ymax/Xmax)
}
dev.off()
for(i in 1:10){
  write.csv(dfs[[i]],file = paste0('~/fuelsgen/examples/bandelier/generated_fuels/generated_fuels/naip/gen_',i,'.csv'))
}
```

# generate no naip fuels

```{r, echo=F}
reps = 10
params = matrix(nrow=reps,ncol=4)
fuels = vector(mode='list',length=nrow(all_topo))
mcmc.list = vector(mode='list',length=3)
for(i in 1:3){
  load(paste0(here('examples/bandelier/results/mcmc/calib_cl_'),i,'.RData'))
  mcmc.list[[i]] = mcmc; rm(mcmc)
}
for(j in 1:nrow(all_topo)){
  fuels[[j]] = vector(mode='list',length=reps)
  # for each grid cell generate fuels w.r.t. cluster membership
  cluster = all_topo$cl[j]
  params = mcmc.list[[cluster]]$trace[sample(1:nrow(mcmc.list[[cluster]]$trace),10,F),]
  for(i in 1:reps){
     fuels[[j]][[i]] = gen_fuels(20,20,params[i,4],params[i,2],params[i,3],1,0,params[i,1],verbose = F)
  }
}
save(fuels,file='~/fuelsgen/examples/bandelier/generated_fuels/no naip/fuelsgen_object.RData')

# linear model from radius to height
r = h = numeric()
for(i in 1:length(data$dat)){
  r = c(r,data$dat[[i]]$r)
  h = c(h,data$dat[[i]]$h)
}
df_rh = data.frame(r=r,h=h)
h3 = which(h>2.99)
df_rh$h3 = 0
df_rh$h3[h3] = 1
mod_rh = lm(h~1+r,df_rh) # model using all data
mod_rh_3 = lm(h~1+r,subset(df_rh,h3==0)) # model not including data where heights have been truncated

plot(df_rh$r,df_rh$h,xlim=c(0,3),ylim=c(0,3))
lines(df_rh$r,mod_rh$fitted.values,col='red')
lines(df_rh$r[df_rh$h3==0],mod_rh_3$fitted.values,col='blue')

# convert to 10 data frames and sample heights 
# Niko xmax = 1040 ymax = 980 
Xmax = 1000 # (coords to 1020) 
Ymax = 940 # coords to 960
dfs = vector(mode='list',length=10)
for(i in 1:10){
  for(j in 156:nrow(all_topo)){ # accidentally generated fuels for plot [1:155] locations, only need grid locations [156:2603]
    dfs[[i]] = rbind(dfs[[i]],data.frame(X=fuels[[j]][[i]]$dat[[1]]$X + (all_topo$x_crd[j] * Xmax),
                                         Y=fuels[[j]][[i]]$dat[[1]]$Y + (all_topo$y_crd[j] * Ymax),
                                         r=fuels[[j]][[i]]$dat[[1]]$r))
  }
  # sample from truncated normal for heights
  rs = predict(mod_rh,data.frame(r=dfs[[i]]$r))
  for(k in 1:length(rs)){
    dfs[[i]]$h[k] = truncdist::rtrunc(1,'norm',a=1,b=3,mean=rs[k],sd=sigma(mod_rh))
  }
}

par(mfrow=c(3,4),mar=c(1,1,1,1))
for(i in 1:10){
  plot(dfs[[i]]$X,dfs[[i]]$Y,pch=16,cex=.2)
}
for(i in 1:10){
  write.csv(dfs[[i]],file = paste0('~/fuelsgen/examples/bandelier/generated_fuels/generated_fuels/no naip/gen_',i,'.csv'))
}
```

